// Theme Presets - Ready-made color schemes
// Users can apply these with one click from Settings

export const themePresets = [
  {
    id: 'default-dark',
    name: 'Default Dark',
    description: 'Original dark theme',
    icon: '🌙',
    theme: {
      app: {
        windowBg: '#0F172A',
        cardBg: '#1E293B',
        elevatedBg: '#334155',
        hoverBg: '#3E4C63',
        border: 'rgba(148, 163, 184, 0.15)',
        textPrimary: '#F1F5F9',
        textSecondary: '#CBD5E1',
        textMuted: '#94A3B8',
        accentBlue: '#3B82F6',
        accentGreen: '#10B981',
        accentRed: '#EF4444',
        accentOrange: '#F59E0B',
        accentPurple: '#8B5CF6',
        accentActiveTask: '#34D399',
      },
    },
  },
  {
    id: 'default-light',
    name: 'Default Light',
    description: 'Clean and bright',
    icon: '☀️',
    theme: {
      app: {
        windowBg: '#F8FAFC',
        cardBg: '#FFFFFF',
        elevatedBg: '#F1F5F9',
        hoverBg: '#E2E8F0',
        border: 'rgba(71, 85, 105, 0.15)',
        textPrimary: '#0F172A',
        textSecondary: '#475569',
        textMuted: '#64748B',
        accentBlue: '#2563EB',
        accentGreen: '#059669',
        accentRed: '#DC2626',
        accentOrange: '#D97706',
        accentPurple: '#7C3AED',
        accentActiveTask: '#10B981',
      },
    },
  },
  {
    id: 'midnight',
    name: 'Midnight',
    description: 'Deep purple accents',
    icon: '🌆',
    theme: {
      app: {
        windowBg: '#0F0A1F',
        cardBg: '#1A1232',
        elevatedBg: '#2D1F4A',
        hoverBg: '#3D2A5F',
        border: 'rgba(167, 139, 250, 0.15)',
        textPrimary: '#F1F0FF',
        textSecondary: '#D4C5FF',
        textMuted: '#A78BFA',
        accentBlue: '#818CF8',
        accentGreen: '#34D399',
        accentRed: '#F87171',
        accentOrange: '#FBBF24',
        accentPurple: '#A78BFA',
        accentActiveTask: '#A78BFA',
      },
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    description: 'Cool blue tones',
    icon: '🌊',
    theme: {
      app: {
        windowBg: '#0A1929',
        cardBg: '#0F2942',
        elevatedBg: '#1A3A52',
        hoverBg: '#244B66',
        border: 'rgba(56, 189, 248, 0.15)',
        textPrimary: '#E0F2FE',
        textSecondary: '#BAE6FD',
        textMuted: '#7DD3FC',
        accentBlue: '#38BDF8',
        accentGreen: '#2DD4BF',
        accentRed: '#FB7185',
        accentOrange: '#FDBA74',
        accentPurple: '#C084FC',
        accentActiveTask: '#2DD4BF',
      },
    },
  },
  {
    id: 'slate',
    name: 'Slate',
    description: 'Neutral grays',
    icon: '⚫',
    theme: {
      app: {
        windowBg: '#0F1419',
        cardBg: '#1C2128',
        elevatedBg: '#2D333B',
        hoverBg: '#373E47',
        border: 'rgba(148, 163, 184, 0.15)',
        textPrimary: '#E6EDF3',
        textSecondary: '#C9D1D9',
        textMuted: '#8B949E',
        accentBlue: '#58A6FF',
        accentGreen: '#3FB950',
        accentRed: '#F85149',
        accentOrange: '#D29922',
        accentPurple: '#BC8CFF',
        accentActiveTask: '#3FB950',
      },
    },
  },
];
